name: Test access to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write


jobs:
  test-access:
    uses: pazdedav/pazdedav/.github/workflows/platform.template.test-access-az.yml@master
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}